destination: _site/
url: "http://127.0.0.1:4011"
baseurl: "/hskwordlist-pdf"
port: 4011
output: pdf
product: hskwordlist
print_title: Product 1 documentation
print_subtitle: version 1.0
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: product1_sidebar
